name: Build and Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 连接服务器拉取代码部署
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.UCLOUD_HOST }}
          username: ${{ secrets.UCLOUD_USERNAME }}
          password: ${{ secrets.UCLOUD_PASSWORD }}
          script: |
            cd /var/next-blog
            git pull origin main
            # 停止并删除之前的容器
            docker stop next-blog || true
            docker rm next-blog || true
            docker build -t next-blog .
            # 运行新的容器
            docker run -d -p 80:3000 next-blog
